language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "5"
  - "4"
before_install: npm i -g depcheck
install:
  - npm i
  - npm link
cache:
  directories:
    - node_modules
    - /home/travis/.diamond